apiVersion: kubeadm.k8s.io/v1beta4
bootstrapTokens:
  - description: kubeadm bootstrap token
    groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: cefac6.4846896c0809bd72
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.11.114
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
  name: k8s-cp-4
  taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
timeouts:
  controlPlaneComponentHealthCheck: 4m0s
  discovery: 5m0s
  etcdAPICall: 2m0s
  kubeletHealthCheck: 4m0s
  kubernetesAPICall: 1m0s
  tlsBootstrap: 5m0s
  upgradeManifests: 5m0s
---
apiServer: {}
apiVersion: kubeadm.k8s.io/v1beta4
caCertificateValidityPeriod: 87600h0m0s
certificateValidityPeriod: 8760h0m0s
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: 192.168.11.110:8443
controllerManager:
  extraArgs:
    - name: bind-address
      value: 0.0.0.0
dns: {}
encryptionAlgorithm: RSA-2048
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: v1.31.0
networking:
  dnsDomain: cluster.local
  podSubnet: 10.128.0.0/16
  serviceSubnet: 10.96.0.0/16
proxy: {}
scheduler:
  extraArgs:
    - name: bind-address
      value: 0.0.0.0
